server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.13.132.217:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true

#server:
#port: 9001
#spring:
#application:
#name: tensquare-base #指定服务名
#datasource:
#driverClassName: com.mysql.jdbc.Driver
#url: jdbc:mysql://106.13.132.217:3306/tensquare_base?characterEncoding=utf-8
#username: root
#password: root
#jpa:
#database: MySQL
#show-sql: true
#generate-ddl: true